controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_main:
    path: /main
    controller: App\Controller\MainController::show
app_items:
    path: /items
    controller: App\Controller\ItemController::show